version: '2.2'

services:
  redis:
    image: redis:5.0.3-alpine3.9
    command: redis-server
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:

